/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as GiftIndexRouteImport } from './routes/gift/index'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTodoIndexRouteImport } from './routes/_layout/todo/index'
import { Route as LayoutCrudIndexRouteImport } from './routes/_layout/crud/index'
import { Route as LayoutAboutIndexRouteImport } from './routes/_layout/about/index'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftIndexRoute = GiftIndexRouteImport.update({
  id: '/gift/',
  path: '/gift/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTodoIndexRoute = LayoutTodoIndexRouteImport.update({
  id: '/todo/',
  path: '/todo/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCrudIndexRoute = LayoutCrudIndexRouteImport.update({
  id: '/crud/',
  path: '/crud/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAboutIndexRoute = LayoutAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/gift/': typeof GiftIndexRoute
  '/about/': typeof LayoutAboutIndexRoute
  '/crud/': typeof LayoutCrudIndexRoute
  '/todo/': typeof LayoutTodoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/gift': typeof GiftIndexRoute
  '/about': typeof LayoutAboutIndexRoute
  '/crud': typeof LayoutCrudIndexRoute
  '/todo': typeof LayoutTodoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/gift/': typeof GiftIndexRoute
  '/_layout/about/': typeof LayoutAboutIndexRoute
  '/_layout/crud/': typeof LayoutCrudIndexRoute
  '/_layout/todo/': typeof LayoutTodoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gift/' | '/about/' | '/crud/' | '/todo/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gift' | '/about' | '/crud' | '/todo'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/gift/'
    | '/_layout/about/'
    | '/_layout/crud/'
    | '/_layout/todo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  GiftIndexRoute: typeof GiftIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift/': {
      id: '/gift/'
      path: '/gift'
      fullPath: '/gift/'
      preLoaderRoute: typeof GiftIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/todo/': {
      id: '/_layout/todo/'
      path: '/todo'
      fullPath: '/todo/'
      preLoaderRoute: typeof LayoutTodoIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/crud/': {
      id: '/_layout/crud/'
      path: '/crud'
      fullPath: '/crud/'
      preLoaderRoute: typeof LayoutCrudIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/about/': {
      id: '/_layout/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof LayoutAboutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAboutIndexRoute: typeof LayoutAboutIndexRoute
  LayoutCrudIndexRoute: typeof LayoutCrudIndexRoute
  LayoutTodoIndexRoute: typeof LayoutTodoIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAboutIndexRoute: LayoutAboutIndexRoute,
  LayoutCrudIndexRoute: LayoutCrudIndexRoute,
  LayoutTodoIndexRoute: LayoutTodoIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  GiftIndexRoute: GiftIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
